# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Push repo to server
        script:
          - pipe: atlassian/ftp-deploy:0.3.6
            variables:
              USER: $SERVER_USER
              PASSWORD: $SERVER_PASSWORD
              SERVER: $SERVER_IP
              REMOTE_PATH: /home/code
    - step:
        name: Start services 
        script:
          - pipe: atlassian/ssh-run:0.3.1
            variables:
              SSH_USER: $SERVER_SSH_USER
              SERVER: $SERVER_IP
              MODE: 'command'
              COMMAND: >
                sudo chmod -R 777 /home/code/ &&
                cd /home/code &&
                docker-compose  up --build --force-recreate -d
                && docker exec redis sh -c 'chmod 777 -R /data && chmod 777 -R /etc  && chmod 777 -R /var && chmod 777 -R /var/spool && chmod 777 -R /var/spool/cron'

              #  docker-compose  up --force-recreate --build kafka_monitor redis_monitor crawler rest ui kafka-ui -d